-- Seed data generated by https://database.build/db/06uxcld4q4k5oqql
-- Seed data for Game Boards

INSERT INTO game_boards (name, dimensions, rules, current_state, version)

VALUES

('Board 1', '10x10', 'Conway', '0000000000', 1),

('Board 2', '20x20', 'HighLife', '1111111111', 1);


-- Seed data for User Participation

INSERT INTO user_participation (user_id, board_id, cursor_position, contributions, session_id)

VALUES

(gen_random_uuid(), (SELECT id FROM game_boards WHERE name = 'Board 1'), '5,5', 'Added glider', gen_random_uuid()),

(gen_random_uuid(), (SELECT id FROM game_boards WHERE name = 'Board 2'), '10,10', 'Removed block', gen_random_uuid());


-- Seed data for Pattern Evolution

INSERT INTO pattern_evolution (board_id, pattern, frequency, ai_suggestions, performance_metrics, evolution_history)

VALUES

((SELECT id FROM game_boards WHERE name = 'Board 1'), 'Glider', 5, 'Try blinker', 'Fast', 'Evolved to blinker'),

((SELECT id FROM game_boards WHERE name = 'Board 2'), 'Block', 3, 'Try toad', 'Moderate', 'Evolved to toad');


-- Seed data for Scheduled Events

INSERT INTO scheduled_events (board_id, event_type, effects, outcomes, event_history)

VALUES

((SELECT id FROM game_boards WHERE name = 'Board 1'), 'Meteor Shower', 'Random cells activated', 'Increased activity', 'Event executed successfully'),

((SELECT id FROM game_boards WHERE name = 'Board 2'), 'Solar Flare', 'All cells reset', 'Board cleared', 'Event executed successfully');


-- Seed data for Analytics

INSERT INTO analytics (board_id, activity_metrics, performance_data, user_engagement)

VALUES

((SELECT id FROM game_boards WHERE name = 'Board 1'), 'High activity', 'Optimal', 'Engaged users'),

((SELECT id FROM game_boards WHERE name = 'Board 2'), 'Moderate activity', 'Suboptimal', 'Less engaged users');